/** Generated by YAKINDU Statechart Tools code generator. */
package traffic.light.trafficlightctrl;

import java.util.LinkedList;
import java.util.List;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;
import traffic.light.ITimer;

public class TrafficLightCtrlStatemachine implements ITrafficLightCtrlStatemachine {
	protected class SCInterfaceImpl implements SCInterface {
	
		private long redPeriod;
		
		public synchronized long getRedPeriod() {
			return redPeriod;
		}
		
		public synchronized void setRedPeriod(long value) {
			this.redPeriod = value;
		}
		
		private long greenPeriod;
		
		public synchronized long getGreenPeriod() {
			return greenPeriod;
		}
		
		public synchronized void setGreenPeriod(long value) {
			this.greenPeriod = value;
		}
		
		private long yellowPeriod;
		
		public synchronized long getYellowPeriod() {
			return yellowPeriod;
		}
		
		public synchronized void setYellowPeriod(long value) {
			this.yellowPeriod = value;
		}
		
	}
	
	
	protected class SCITrafficLightImpl implements SCITrafficLight {
	
		private List<SCITrafficLightListener> listeners = new LinkedList<SCITrafficLightListener>();
		
		public List<SCITrafficLightListener> getListeners() {
			return listeners;
		}
		private boolean displayRed;
		
		
		public synchronized boolean isRaisedDisplayRed() {
			return displayRed;
		}
		
		protected void raiseDisplayRed() {
			displayRed = true;
			for (SCITrafficLightListener listener : listeners) {
				listener.onDisplayRedRaised();
			}
		}
		
		private boolean displayGreen;
		
		
		public synchronized boolean isRaisedDisplayGreen() {
			return displayGreen;
		}
		
		protected void raiseDisplayGreen() {
			displayGreen = true;
			for (SCITrafficLightListener listener : listeners) {
				listener.onDisplayGreenRaised();
			}
		}
		
		private boolean displayYellow;
		
		
		public synchronized boolean isRaisedDisplayYellow() {
			return displayYellow;
		}
		
		protected void raiseDisplayYellow() {
			displayYellow = true;
			for (SCITrafficLightListener listener : listeners) {
				listener.onDisplayYellowRaised();
			}
		}
		
		protected void clearEvents() {
		}
		protected void clearOutEvents() {
		
		displayRed = false;
		displayGreen = false;
		displayYellow = false;
		}
		
	}
	
	
	protected SCInterfaceImpl sCInterface;
	
	protected SCITrafficLightImpl sCITrafficLight;
	
	private boolean initialized = false;
	
	public enum State {
		main_Red,
		main_Green,
		main_Yellow,
		$NullState$
	};
	
	private final State[] stateVector = new State[1];
	
	private int nextStateIndex;
	
	private ITimer timer;
	
	private final boolean[] timeEvents = new boolean[3];
	
	public TrafficLightCtrlStatemachine() {
		sCInterface = new SCInterfaceImpl();
		sCITrafficLight = new SCITrafficLightImpl();
	}
	
	public synchronized void init() {
		this.initialized = true;
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		for (int i = 0; i < 1; i++) {
			stateVector[i] = State.$NullState$;
		}
		clearEvents();
		clearOutEvents();
		sCInterface.setRedPeriod(60);
		
		sCInterface.setGreenPeriod(55);
		
		sCInterface.setYellowPeriod(5);
	}
	
	public synchronized void enter() {
		if (!initialized) {
			throw new IllegalStateException(
				"The state machine needs to be initialized first by calling the init() function."
			);
		}
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		enterSequence_main_default();
	}
	
	public synchronized void runCycle() {
		if (!initialized)
			throw new IllegalStateException(
					"The state machine needs to be initialized first by calling the init() function.");
		clearOutEvents();
		for (nextStateIndex = 0; nextStateIndex < stateVector.length; nextStateIndex++) {
			switch (stateVector[nextStateIndex]) {
			case main_Red:
				main_Red_react(true);
				break;
			case main_Green:
				main_Green_react(true);
				break;
			case main_Yellow:
				main_Yellow_react(true);
				break;
			default:
				// $NullState$
			}
		}
		clearEvents();
	}
	public synchronized void exit() {
		exitSequence_main();
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public synchronized boolean isActive() {
		return stateVector[0] != State.$NullState$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public synchronized boolean isFinal() {
		return false;
	}
	/**
	* This method resets the incoming events (time events included).
	*/
	protected void clearEvents() {
		sCITrafficLight.clearEvents();
		for (int i=0; i<timeEvents.length; i++) {
			timeEvents[i] = false;
		}
	}
	
	/**
	* This method resets the outgoing events.
	*/
	protected void clearOutEvents() {
		sCITrafficLight.clearOutEvents();
	}
	
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public synchronized boolean isStateActive(State state) {
	
		switch (state) {
		case main_Red:
			return stateVector[0] == State.main_Red;
		case main_Green:
			return stateVector[0] == State.main_Green;
		case main_Yellow:
			return stateVector[0] == State.main_Yellow;
		default:
			return false;
		}
	}
	
	/**
	* Set the {@link ITimer} for the state machine. It must be set
	* externally on a timed state machine before a run cycle can be correctly
	* executed.
	* 
	* @param timer
	*/
	public synchronized void setTimer(ITimer timer) {
		this.timer = timer;
	}
	
	/**
	* Returns the currently used timer.
	* 
	* @return {@link ITimer}
	*/
	public ITimer getTimer() {
		return timer;
	}
	
	public synchronized void timeElapsed(int eventID) {
		timeEvents[eventID] = true;
		runCycle();
	}
	
	public SCInterface getSCInterface() {
		return sCInterface;
	}
	
	public SCITrafficLight getSCITrafficLight() {
		return sCITrafficLight;
	}
	
	public synchronized long getRedPeriod() {
		return sCInterface.getRedPeriod();
	}
	
	public synchronized void setRedPeriod(long value) {
		sCInterface.setRedPeriod(value);
	}
	
	public synchronized long getGreenPeriod() {
		return sCInterface.getGreenPeriod();
	}
	
	public synchronized void setGreenPeriod(long value) {
		sCInterface.setGreenPeriod(value);
	}
	
	public synchronized long getYellowPeriod() {
		return sCInterface.getYellowPeriod();
	}
	
	public synchronized void setYellowPeriod(long value) {
		sCInterface.setYellowPeriod(value);
	}
	
	/* Entry action for state 'Red'. */
	private void entryAction_main_Red() {
		timer.setTimer(this, 0, (sCInterface.getRedPeriod() * 1000), false);
		
		sCITrafficLight.raiseDisplayRed();
	}
	
	/* Entry action for state 'Green'. */
	private void entryAction_main_Green() {
		timer.setTimer(this, 1, (sCInterface.getGreenPeriod() * 1000), false);
		
		sCITrafficLight.raiseDisplayGreen();
	}
	
	/* Entry action for state 'Yellow'. */
	private void entryAction_main_Yellow() {
		timer.setTimer(this, 2, (sCInterface.getYellowPeriod() * 1000), false);
		
		sCITrafficLight.raiseDisplayYellow();
	}
	
	/* Exit action for state 'Red'. */
	private void exitAction_main_Red() {
		timer.unsetTimer(this, 0);
	}
	
	/* Exit action for state 'Green'. */
	private void exitAction_main_Green() {
		timer.unsetTimer(this, 1);
	}
	
	/* Exit action for state 'Yellow'. */
	private void exitAction_main_Yellow() {
		timer.unsetTimer(this, 2);
	}
	
	/* 'default' enter sequence for state Red */
	private void enterSequence_main_Red_default() {
		entryAction_main_Red();
		nextStateIndex = 0;
		stateVector[0] = State.main_Red;
	}
	
	/* 'default' enter sequence for state Green */
	private void enterSequence_main_Green_default() {
		entryAction_main_Green();
		nextStateIndex = 0;
		stateVector[0] = State.main_Green;
	}
	
	/* 'default' enter sequence for state Yellow */
	private void enterSequence_main_Yellow_default() {
		entryAction_main_Yellow();
		nextStateIndex = 0;
		stateVector[0] = State.main_Yellow;
	}
	
	/* 'default' enter sequence for region main */
	private void enterSequence_main_default() {
		react_main__entry_Default();
	}
	
	/* Default exit sequence for state Red */
	private void exitSequence_main_Red() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_main_Red();
	}
	
	/* Default exit sequence for state Green */
	private void exitSequence_main_Green() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_main_Green();
	}
	
	/* Default exit sequence for state Yellow */
	private void exitSequence_main_Yellow() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_main_Yellow();
	}
	
	/* Default exit sequence for region main */
	private void exitSequence_main() {
		switch (stateVector[0]) {
		case main_Red:
			exitSequence_main_Red();
			break;
		case main_Green:
			exitSequence_main_Green();
			break;
		case main_Yellow:
			exitSequence_main_Yellow();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_main__entry_Default() {
		enterSequence_main_Red_default();
	}
	
	private boolean react() {
		return false;
	}
	
	private boolean main_Red_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[0]) {
				exitSequence_main_Red();
				enterSequence_main_Green_default();
				react();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_Green_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[1]) {
				exitSequence_main_Green();
				enterSequence_main_Yellow_default();
				react();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_Yellow_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[2]) {
				exitSequence_main_Yellow();
				enterSequence_main_Red_default();
				react();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
}
